### ISSUE TITLE
No PlatformIO.ini entry for Pico W

### ISSUE THREAD

**Issue by bscherer-sdvi** [adafruit/Adafruit_Wippersnapper_Arduino#467]
**Describe the bug**
Cant build for Pico W in PlatformIO (while Pico is a supported board for WipperSnapper, theres no PlatformIO.ini entry)

***Arduino board***
Pico W

**To Reproduce**
Trying building for Pico W in PlatformIO

**Expected behavior**
The ability to build for Pico W

**Which components are connected to your device**
Which components are set up on the WipperSnapper device page?

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by bscherer-sdvi** [comment]
I tried writing my own section but went down a dependency hell-hole where I couldnt seem to find some dependencies

```
[env:raspberrypi_pico_w]
platform = raspberrypi
board = pico
lib_ldf_mode = deep+
build_flags = -DUSE_TINYUSB=1
	-DARDUINO_RASPBERRY_PI_PICO_W
```

**Comment by brentru** [comment]
@bscherer-sdvi Unfortunately,  RaspberryPi Trading Ltd. had a disagreement with PlatformIO Labs when it came to adding the Earlephilhower Arduino Pico core, the full details are on this PR: https://github.com/platformio/platform-raspberrypi/pull/36. The result is that [there is no platformio package for the rp2040 anymore. ](https://github.com/earlephilhower/arduino-pico/issues/1617#issuecomment-1657116853).

As a result, I recommend compiling WipperSnapper for PicoW using the Earlephilhower and Arduino IDE.

I can leave this issue open if you're interested in trying out max's solution in (https://github.com/earlephilhower/arduino-pico/issues/1617), otherwise I will close it.

**Comment by bscherer-sdvi** [comment]
Thanks for the quick reply! I will try whats in that repo. Go ahead an close :)

**Comment by bscherer-sdvi** [comment]
err I can i see
